Repository pknu-wap/Dokdo_Public, pull requests merged in 2024-11, with the labels that each got.

#39 Feature/32 Design 애니메이션 수정
  client/jsconfig.json
  client/netlify.toml
  client/src/assets/stage2/BoxOpenAfter.png
  client/src/components/Book.js
  client/src/components/Book.module.css
  client/src/components/Inventory.js
  client/src/pages/Stage2Page.js
  client/src/pages/Stage3Page.js
Labels: 💖DESIGN💖, 🐰정아란🐰, Front-End

#42 Fix: 시작화면, 뉴스화면, Stage1 이미지 용량 최적화
  client/src/assets/News1.png
  client/src/assets/News2.png
  client/src/assets/StartBg.png
  client/src/assets/logo2.png
  client/src/assets/stage1/Music.png
  client/src/assets/stage1/RedItem.png
  client/src/assets/stage1/Stage1DoorClose.png
  client/src/assets/stage1/Stage1DoorOpen.png
  client/src/assets/stage1/Stage1DrawerClose.png
  client/src/assets/stage1/Stage1DrawerOpen.png
Labels: 🐞BUG🐞, 🐻‍❄️임가은🐻‍❄️, Front-End

#46 Feature/45 feat swagger 설정
  sever/build.gradle
  sever/src/main/java/com/example/rememberdokdo/Config/SwaggerConfig.java
Labels: 🌟FEATURE🌟, 🐣백채연🐣, Back-End

#48 Feature/44 feat stage2 드래그기능 & css 수정
  client/src/assets/stage2/BookShelf.png
  client/src/assets/stage2/Box.png
  client/src/assets/stage2/BoxOpenAfter.png
  client/src/assets/stage2/Door.png
  client/src/assets/stage2/DoorOpen.png
  client/src/assets/stage2/Lamp.png
  client/src/assets/stage2/Map.png
  client/src/assets/stage2/OpenBook.png
  client/src/assets/stage2/OpenBox.png
  client/src/components/Book.module.css
  client/src/components/CheckNumber.module.css
  client/src/components/Inventory.js
  client/src/pages/Stage2Page.js
  client/src/pages/Stage2Page.module.css
Labels: 🌟FEATURE🌟, 🐰정아란🐰, Front-End

#50 Feature/47 feat 중간발표 배포 이후 버그수정
  client/src/assets/GunHintImage.png
  client/src/assets/KoreaFlag.png
  client/src/assets/Stage3wall.png
  client/src/assets/stage3/GunHintImage.png
  client/src/assets/stage3/KoreaFlag.png
  client/src/assets/stage3/SpyHintImage.png
  client/src/assets/stage3/Stage3DoorClose.png
  client/src/assets/stage3/Stage3DoorOpen.png
  client/src/assets/stage3/Stage3wall.png
  client/src/assets/stage3/게임 화면_ 바닥.png
  client/src/assets/stage3/게임 화면_ 배경.png
  client/src/assets/stage3/국기1.png
  client/src/assets/stage3/국기10.png
  client/src/assets/stage3/국기11.png
  client/src/assets/stage3/국기12.png
  client/src/assets/stage3/국기13.png
  client/src/assets/stage3/국기14.png
  client/src/assets/stage3/국기2.png
  client/src/assets/stage3/국기3.png
  client/src/assets/stage3/국기4.png
  client/src/assets/stage3/국기5.png
  client/src/assets/stage3/국기6.png
  client/src/assets/stage3/국기7.png
  client/src/assets/stage3/국기8.png
  client/src/assets/stage3/국기9.png
  client/src/assets/stage3/상단바_ 배경.png
  client/src/assets/stage3/상단바_ 클릭하기 전-1.png
  client/src/assets/stage3/상단바_ 클릭하기 전.png
  client/src/assets/stage3/상단바_ 클릭한 후.png
  client/src/assets/stage3/인벤토리_ 배경.png
  client/src/assets/stage3/인벤토리_ 아이템함.png
  client/src/assets/stage3/인벤토리_ 화살표.png
  client/src/assets/stage3/친일파 힌트 임시종이.png
  client/src/assets/stage3/친일파(1).png
  client/src/assets/stage3/친일파(10).png
  client/src/assets/stage3/친일파(11).png
  client/src/assets/stage3/친일파(12).png
  client/src/assets/stage3/친일파(2).png
  client/src/assets/stage3/친일파(3).png
  client/src/assets/stage3/친일파(4).png
  client/src/assets/stage3/친일파(5).png
  client/src/assets/stage3/친일파(6).png
  client/src/assets/stage3/친일파(7).png
  client/src/assets/stage3/친일파(8).png
  client/src/assets/stage3/친일파(9).png
  client/src/assets/stage3/큰 액자.png
  client/src/assets/친일파(1).png
  client/src/assets/친일파(2).png
  client/src/assets/친일파(3).png
  client/src/assets/친일파(4).png
  client/src/assets/친일파(5).png
  client/src/assets/친일파(6).png
  client/src/components/Inventory.js
  client/src/pages/Stage3Page.js
  client/src/pages/Stage3Page.module.css
Labels: 🌟FEATURE🌟, 🎀김효원🎀, Front-End

#55 Feature/53 feat stage4 room1 2 3 구현
  .gitignore
  client/package-lock.json
  client/src/Main.js
  client/src/assets/clover2.png
  client/src/assets/clover3.png
  client/src/assets/clover4.png
  client/src/assets/stage3/GunHintImage.png
  client/src/assets/stage3/SpyHintImage.png
  client/src/assets/stage3/Stage3wall.png
  client/src/assets/stage3/친일파(1).png
  client/src/assets/stage3/친일파(10).png
  client/src/assets/stage3/친일파(11).png
  client/src/assets/stage3/친일파(12).png
  client/src/assets/stage3/친일파(2).png
  client/src/assets/stage3/친일파(3).png
  client/src/assets/stage3/친일파(6).png
  client/src/assets/stage3/친일파(8).png
  client/src/assets/stage3/친일파(9).png
  client/src/assets/stage4/Bibimbap.png
  client/src/assets/stage4/Bomb.png
  client/src/assets/stage4/Dokki.png
  client/src/assets/stage4/Eomuk.png
  client/src/assets/stage4/Gun_Black.png
  client/src/assets/stage4/Gun_Gray.png
  client/src/assets/stage4/Gun_White.png
  client/src/assets/stage4/Hallabong.png
  client/src/assets/stage4/Heart.png
  client/src/assets/stage4/KimChunsam.png
  client/src/assets/stage4/ParkHwanyoung.png
  client/src/assets/stage4/SonJeongpal.png
  client/src/assets/stage4/Table.png
  client/src/assets/stage4/TopBar.png
  client/src/assets/stage4/Yeontan.png
  client/src/components/CheckNumber.js
  client/src/components/CheckNumber.module.css
  client/src/components/GameOver.js
  client/src/components/GameOver.module.css
  client/src/components/Inventory.js
  client/src/context/InventoryContext2.js
  client/src/context/UserContext.js
  client/src/pages/Stage1Page.js
  client/src/pages/Stage3Page.js
  client/src/pages/Stage3Page.module.css
  client/src/pages/Stage4Room1.js
  client/src/pages/Stage4Room1.module.css
  client/src/pages/Stage4Room2.js
  client/src/pages/Stage4Room2.module.css
  client/src/pages/Stage4Room3.js
  client/src/pages/Stage4Room3.module.css
  package-lock.json
  package.json
Labels: 🌟FEATURE🌟, 🎀김효원🎀, Front-End

#59 Feature/51 feat stage4 room4 구현
  client/src/Main.js
  client/src/assets/dokdoPuzzle1.png
  client/src/assets/dokdoPuzzle2.png
  client/src/assets/dokdoPuzzle3.png
  client/src/assets/dokdoPuzzle4.png
  client/src/assets/dokdoPuzzleNone.png
  client/src/assets/stage2/CodeNote.png
  client/src/assets/stage2/CodeNoteCut.png
  client/src/assets/stage2/timeLocationHint.png
  client/src/assets/stage2/timeLocationHintCut.png
  client/src/assets/stage4Room3/person.png
  client/src/components/Book.js
  client/src/components/CheckNumber.module.css
  client/src/components/Inventory.js
  client/src/pages/EndFailPage.js
  client/src/pages/EndFailPage.module.css
  client/src/pages/Stage1Page.js
  client/src/pages/Stage2Page.js
  client/src/pages/Stage2Page.module.css
  client/src/pages/Stage4PuzzleGame.js
  client/src/pages/Stage4PuzzleGame.module.css
Labels: 🌟FEATURE🌟, 🐰정아란🐰, Front-End

#70 Fix: 원활한 게임을 위한 CSS수정
  client/src/pages/Stage3Page.js
  client/src/pages/Stage3Page.module.css
Labels: 🌟FEATURE🌟, 🎀김효원🎀, Front-End

#75 Feature/49 feat 스테이지4 진행 상황 기능
  sever/src/main/java/com/example/rememberdokdo/Controller/StageController.java
  sever/src/main/java/com/example/rememberdokdo/Dto/SessionProgressDto.java
  sever/src/main/java/com/example/rememberdokdo/Dto/Stage4ItemDto.java
  sever/src/main/java/com/example/rememberdokdo/Dto/StageProgressResponseDto.java
  sever/src/main/java/com/example/rememberdokdo/Dto/StageResetResponseDto.java
  sever/src/main/java/com/example/rememberdokdo/Entity/Stage4ItemEntity.java
  sever/src/main/java/com/example/rememberdokdo/Entity/StageProgressEntity.java
  sever/src/main/java/com/example/rememberdokdo/Exception/StageExceptionHandler.java
  sever/src/main/java/com/example/rememberdokdo/Repository/Inventory/InventoryItemsRepository.java
  sever/src/main/java/com/example/rememberdokdo/Repository/Inventory/InventoryRepository.java
  sever/src/main/java/com/example/rememberdokdo/Repository/Stage4ItemRepository.java
  sever/src/main/java/com/example/rememberdokdo/Repository/StageProgressRepository.java
  sever/src/main/java/com/example/rememberdokdo/Service/SessionService.java
  sever/src/main/java/com/example/rememberdokdo/Service/StageResetService.java
  sever/src/main/java/com/example/rememberdokdo/Service/StageService.java
Labels: 🌟FEATURE🌟, 🔮REFEACTOR🔮, 🐧김수현🐧, Back-End

#78 Bug/77 bug 스테이지 초기화 버그 수정
  sever/src/main/java/com/example/rememberdokdo/Controller/StageController.java
  sever/src/main/java/com/example/rememberdokdo/Controller/StageResetController.java
  sever/src/main/java/com/example/rememberdokdo/Repository/StageProgressRepository.java
  sever/src/main/java/com/example/rememberdokdo/Service/StageResetService.java
Labels: 🐞BUG🐞, 🐧김수현🐧, Back-End

#80 Feature/73 feat 독도 퍼즐 연동 및 UI 마무리
  client/src/pages/Stage3Page.module.css
  client/src/pages/Stage4Room1.js
  client/src/pages/Stage4Room1.module.css
  client/src/pages/Stage4Room2.js
  client/src/pages/Stage4Room2.module.css
  client/src/pages/Stage4Room3.js
  client/src/pages/Stage4Room3.module.css
Labels: 💖DESIGN💖, 🐻‍❄️임가은🐻‍❄️, Front-End

#81 Feature/60 feat 아이템 delete기능 적용
  client/src/assets/LeftPage.png
  client/src/assets/OpenBook.png
  client/src/assets/RightPage.png
  client/src/assets/Stage2Box.png
  client/src/assets/Stage2BoxOpen.png
  client/src/assets/Stage2Door.png
  client/src/assets/Stage2Map.png
  client/src/assets/clover.png
  client/src/assets/clover2.png
  client/src/assets/clover3.png
  client/src/assets/clover4.png
  client/src/assets/dokdoPuzzle2.png
  client/src/assets/dokdoPuzzle2_2.png
  client/src/assets/dokdoPuzzle3.png
  client/src/assets/dokdoPuzzle3_2.png
  client/src/assets/dokdoPuzzle4.png
  client/src/assets/dokdoPuzzle4_2.png
  client/src/assets/puzzle안내.png
  client/src/components/Book.module.css
  client/src/components/CheckNumber.module.css
  client/src/context/UserContext.js
  client/src/pages/EndFailPage.js
  client/src/pages/EndFailPage.module.css
  client/src/pages/Stage2Page.js
  client/src/pages/Stage2Page.module.css
  client/src/pages/Stage4PuzzleGame.js
  client/src/pages/Stage4PuzzleGame.module.css
Labels: 🌟FEATURE🌟, 🐰정아란🐰, Front-End

#82 Feature/74 feat final
  client/src/Main.js
  client/src/assets/stage3/Stage3wall.png
  client/src/assets/stage3/친일파(2).png
  client/src/assets/stage3/친일파(3).png
  client/src/assets/stage3/친일파(4).png
  client/src/assets/stage3/친일파(5).png
  client/src/assets/stage3/친일파(7).png
  client/src/pages/GameOver.js
  client/src/pages/GameOver.module.css
  client/src/pages/Stage3Page.js
  client/src/pages/Stage4Room3.js
Labels: 🌟FEATURE🌟, 🎀김효원🎀, Front-End

#84 Feat: 성공페이지 구현
  client/src/Main.js
  client/src/assets/letter.png
  client/src/pages/EndSuccessPage.js
  client/src/pages/EndSuccessPage.module.css
  client/src/pages/GameOver.js
  client/src/pages/GameOver.module.css
  client/src/pages/Stage4PuzzleGame.js
Labels: 🌟FEATURE🌟, 🐰정아란🐰, Front-End

#90 Fix: 책 안열리는 버그 수정
  client/src/components/Book.module.css
  client/src/pages/Stage2Page.js
Labels: 🌟FEATURE🌟, 🐰정아란🐰, Front-End
