Repository pknu-wap/Dokdo_Public, pull requests merged in 2024-10, with the labels that each got.

#16 Feature/5 feat Stage2 지도 암호 구현
  client/src/assets/BookShelf.jpg
  client/src/assets/LeftPage.png
  client/src/assets/OpenBook.png
  client/src/assets/RightPage.png
  client/src/assets/Stage2Map.png
  client/src/components/Book.js
  client/src/components/Book.module.css
  client/src/pages/IntroPage.js
  client/src/pages/IntroPage.module.css
  client/src/pages/NewsPage.js
  client/src/pages/Stage1Page.js
  client/src/pages/Stage1Page.module.css
  client/src/pages/Stage2Page.css
  client/src/pages/Stage2Page.js
  client/src/pages/Stage2Page.module.css
Labels: 🌟FEATURE🌟, 🐰정아란🐰, Front-End

#22 Feature/21 feat stage1 오브젝트 확대 및 아이템 확대
  client/src/components/Inventory.js
  client/src/components/Inventory.module.css
  client/src/components/ToolBar.module.css
  client/src/index.css
  client/src/pages/Stage1Page.js
  client/src/pages/Stage1Page.module.css
  client/src/pages/StartPage.js
Labels: 🌟FEATURE🌟, 🐻‍❄️임가은🐻‍❄️, Front-End

#25 Feature/2 feat 아이템 관리 기능
  sever/src/main/java/com/example/rememberdokdo/Controller/InventoryController.java
  sever/src/main/java/com/example/rememberdokdo/Dto/Inventory/ItemAddRequestDto.java
  sever/src/main/java/com/example/rememberdokdo/Dto/Inventory/ItemAddResponseDto.java
  sever/src/main/java/com/example/rememberdokdo/Dto/Inventory/ItemDeleteRequestDto.java
  sever/src/main/java/com/example/rememberdokdo/Dto/Inventory/ItemDeleteResponseDto.java
  sever/src/main/java/com/example/rememberdokdo/Entity/Inventory/InventoryEntity.java
  sever/src/main/java/com/example/rememberdokdo/Entity/Inventory/InventoryItemsEntity.java
  sever/src/main/java/com/example/rememberdokdo/Entity/Inventory/ItemsEntity.java
  sever/src/main/java/com/example/rememberdokdo/Repository/Inventory/InventoryItemsRepository.java
  sever/src/main/java/com/example/rememberdokdo/Repository/Inventory/InventoryRepository.java
  sever/src/main/java/com/example/rememberdokdo/Repository/Inventory/ItemsRepository.java
  sever/src/main/java/com/example/rememberdokdo/Service/Inventory/InventoryAddItemsService.java
  sever/src/main/java/com/example/rememberdokdo/Service/Inventory/InventoryDeleteItemsService.java
  sever/src/main/resources/application-aws.properties
  sever/src/main/resources/application.properties
Labels: 🌟FEATURE🌟, 🐧김수현🐧, Back-End

#27 Feature/23 feat 뉴스 화면 수정
  client/src/components/Modal.module.css
  client/src/pages/NewsPage.js
  client/src/pages/NewsPage.module.css
  client/src/pages/StartPage.module.css
Labels: 🌟FEATURE🌟, 🐻‍❄️임가은🐻‍❄️, Front-End

#13 Feature/12 feat 사진 팝업 제작
  README.md
  client/package-lock.json
  client/src/Main.js
  client/src/assets/BookShelf.jpg
  client/src/assets/Down.png
  client/src/assets/GunHintImage.png
  client/src/assets/KoreaFlag.png
  client/src/assets/Stage2Box.png
  client/src/assets/Stage2BoxOpen.png
  client/src/assets/Up.png
  client/src/assets/background.png
  client/src/assets/stage3wall.png
  client/src/assets/친일파(1).png
  client/src/assets/친일파(2).png
  client/src/assets/친일파(3).png
  client/src/assets/친일파(4).png
  client/src/assets/친일파(5).png
  client/src/assets/친일파(6).png
  client/src/components/Book.js
  client/src/components/Book.module.css
  client/src/components/CheckNumber.js
  client/src/components/CheckNumber.module.css
  client/src/components/Inventory.js
  client/src/components/Inventory.module.css
  client/src/context/InventoryContext.js
  client/src/fonts/MapoAgape.ttf
  client/src/pages/Stage2Page.js
  client/src/pages/Stage2Page.module.css
  client/src/pages/Stage3Page.js
  client/src/pages/Stage3Page.module.css
  package-lock.json
Labels: 🌟FEATURE🌟, 🎀김효원🎀, Front-End

#28 Feature/17 feat 정답 입력창 구현
  client/src/components/Book.js
  client/src/components/Book.module.css
  client/src/components/CheckNumber.module.css
  client/src/components/Inventory.js
  client/src/pages/Stage1Page.js
  client/src/pages/Stage2Page.js
  client/src/pages/Stage2Page.module.css
Labels: 🌟FEATURE🌟, 💖DESIGN💖, 🐰정아란🐰, Front-End

#35 Feature/24 feat 스테이지 연결
  sever/src/main/java/com/example/rememberdokdo/Config/StageConfig.java
  sever/src/main/java/com/example/rememberdokdo/Controller/StageController.java
  sever/src/main/java/com/example/rememberdokdo/Dto/StageDto.java
  sever/src/main/java/com/example/rememberdokdo/Repository/StageProgressRepository.java
  sever/src/main/java/com/example/rememberdokdo/Service/StageService.java
Labels: 🌟FEATURE🌟, 🐣백채연🐣, Back-End

#34 Feature/29 feat mustache 아이템 기능
  sever/src/main/java/com/example/rememberdokdo/Controller/InventoryController.java
  sever/src/main/java/com/example/rememberdokdo/Dto/Inventory/ItemAddRequestDto.java
  sever/src/main/java/com/example/rememberdokdo/Dto/Inventory/ItemDeleteRequestDto.java
  sever/src/main/java/com/example/rememberdokdo/Repository/Inventory/InventoryItemsRepository.java
  sever/src/main/java/com/example/rememberdokdo/Service/Inventory/InventoryAddItemsService.java
  sever/src/main/java/com/example/rememberdokdo/Service/Inventory/InventoryDeleteItemsService.java
  sever/src/main/resources/application.properties
  sever/src/main/resources/templates/.mustache
  sever/src/main/resources/templates/inventoryForm.mustache
  sever/src/main/resources/templates/inventoryItems.mustache
Labels: 🐧김수현🐧, Back-End, 📣DEPLOY📣

#37 Feature/30 feat mustache 세션 화면 구성
  sever/src/main/java/com/example/rememberdokdo/Config/StageConfig.java
  sever/src/main/java/com/example/rememberdokdo/Controller/SessionController.java
  sever/src/main/java/com/example/rememberdokdo/Controller/StageController.java
  sever/src/main/java/com/example/rememberdokdo/Dto/StageDto.java
  sever/src/main/java/com/example/rememberdokdo/Entity/StageProgressEntity.java
  sever/src/main/java/com/example/rememberdokdo/Repository/StageProgressRepository.java
  sever/src/main/java/com/example/rememberdokdo/Service/SessionService.java
  sever/src/main/java/com/example/rememberdokdo/Service/StageService.java
  sever/src/main/resources/application.properties
  sever/src/main/resources/templates/sessionStatus.mustache
Labels: 🐣백채연🐣, Back-End, 📣DEPLOY📣
